### ISSUE TITLE
CssCompressor.java have issues , the 0% shouldn't compress to 0

### ISSUE THREAD

**Issue by perfect** [yui/yuicompressor#184] opened 2014-12-26 07:15 UTC
0% {
		-moz-transform-origin: bottom center;
		-moz-transform: perspective(999px) rotateX(90deg);
		top: -100%;
	}

compreess to 
0   {   	-moz-transform-origin: bottom center;
		-moz-transform: perspective(999px) rotateX(90deg);
		top: -100%;
	}

It's not right. 0%  -->0

**Comment by denizdogan** [comment] 2015-01-19 14:29
Looks like a duplicate of #151

**Comment by perfect** [comment] 2015-01-28 08:27
thank U.  It's a same bug

**Comment by tml** [comment] 2015-01-29 23:05
@perfect maybe you can comment on #151 whether the bug is fixed for you in HEAD?

**Comment by perfect** [comment] 2015-02-09 07:10
@tml    Done

**Comment by tml** [comment] 2015-02-09 07:20
Closed per #151

**Closed by tml** 2015-02-09 07:20 UTC

**Comment by bluemoehre** [comment] 2015-09-11 11:32
Thought this was solved?! Current HEAD fails with this.

**Comment by jochenberger** [comment] 2016-07-22 07:02
Should be fixed in master (see #231)
